spring.application.name=bff
server.port=8085

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.inventario.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventario.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventario.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventario.waitDurationInOpenState=10s

# --- Eureka client ---
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# --- Eureka metadata (links visibles en dashboard) ---
eureka.instance.metadata-map.swagger=http://localhost:8085/swagger-ui.html
eureka.instance.metadata-map.health=http://localhost:8085/actuator/health
eureka.instance.metadata-map.metrics=http://localhost:8085/actuator/metrics
eureka.instance.metadata-map.description=Backend for Frontend - JWT + Circuit Breaker
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.status-page-url=http://localhost:8085/actuator/info
eureka.instance.health-check-url=http://localhost:8085/actuator/health
eureka.instance.home-page-url=http://localhost:8085/swagger-ui.html 

management.info.env.enabled=true
info.app.name=BFF - API Gateway
info.app.description=Backend for Frontend - JWT y Circuit Breaker
info.app.version=1.0.0
info.app.puerto=8085