spring.application.name=envios
server.port=8093

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/envios_db
spring.datasource.username=postgres
spring.datasource.password=Rodrigo2481

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.smartlogix=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always